import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Layout from './components/Layout'
// import NavBar from './NavBar'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NavBar/> */}
      {/* <Layout/> */}
      <div className={styles.main}>
      <h1>Home</h1>
      </div>
    </div>
  )
}